sudo: required
services:
  - docker

before_install:
  - docker build -t ajbenson/docker-react -f Dockerfile.dev .

script:
  - docker run ajbenson/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "dockerreact"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-435085567559"
  bucket_path: "dockerreact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_id: 
    secure: "$AWS_SECRET_KEY"
